SELECT
DISTINCT PAYMENT_METHOD
FROM DEV_BRONZE.CRM_DATA_{{YOUR USERNAME}}.VW_SALES_TRANSACTIONS;

SELECT
DISTINCT INVENTORY_STATUS
FROM DEV_BRONZE.CRM_DATA_{{YOUR USERNAME}}.VW_ARTWORK_INVENTORY;

SELECT
DISTINCT ARTIST_TIER
FROM DEV_BRONZE.CRM_DATA_{{YOUR USERNAME}}.VW_ARTIST_PROFILES;